name: Deploy Landing Page to GitHub Pages

on:
  push:
    branches: [ master ]
    paths:
      - 'landing/**'
  workflow_dispatch: # Allow manual triggering

# Sets permissions for the GITHUB_TOKEN
permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: 'landing/package-lock.json'

      - name: Install dependencies
        run: |
          cd landing
          npm ci

      - name: Build
        run: |
          cd landing
          npm run build

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./landing/dist
          publish_branch: gh-pages
          cname: # Leave empty for username.github.io/repo-name
